import { defineRecipe } from "@chakra-ui/react"

export const linkRecipe = defineRecipe({
  base: {
    _focusVisible: {
      outline: "2px solid",
      outlineColor: "accent.teal",
      outlineOffset: "2px",
    },
  },
  variants: {
    variant: {
      route: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        w: "46px",
        h: "46px",
        borderRadius: "4px",
        border: "1px solid",
        bg: "bg.steelAlpha.60",
        borderColor: "border.inner",
        color: "text.secondary",
        boxShadow: "none",
        transition: "all 0.2s ease",
        textDecoration: "none",
        _hover: {
          bg: "accent.tealAlpha.8",
          borderColor: "accent.teal",
          color: "accent.teal",
          boxShadow: "nav.inactiveHover",
        },
        _currentPage: {
          bg: "accent.tealAlpha.15",
          borderColor: "accent.teal",
          color: "accent.teal",
          boxShadow: "nav.active",
          _hover: {
            bg: "accent.tealAlpha.25",
            borderColor: "accent.teal",
            color: "accent.teal",
            boxShadow: "nav.activeHover",
          },
        },
      },
      projectIcon: {
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        w: "42px",
        h: "42px",
        minH: "42px",
        flexBasis: "42px",
        flexGrow: 0,
        flexShrink: 0,
        p: 0,
        borderRadius: "sm",
        bg: "projectCard.control",
        border: "1px solid",
        borderColor: "border.inner",
        color: "text.primary",
        textStyle: "projectCardAction",
        textDecoration: "none",
        transition: "all 0.2s ease",
        _hover: {
          bg: "projectCard.control",
          borderColor: "accent.teal",
          color: "accent.teal",
        },
      },
      projectAction: {
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        minH: "42px",
        flexShrink: 0,
        px: "0.8rem",
        py: "0.65rem",
        bg: "projectCard.control",
        border: "1px solid",
        borderColor: "border.inner",
        borderRadius: "sm",
        color: "text.primary",
        textStyle: "projectCardAction",
        textDecoration: "none",
        whiteSpace: "nowrap",
        transition: "all 0.2s ease",
        _hover: {
          bg: "projectCard.control",
          borderColor: "accent.teal",
          color: "accent.teal",
        },
      },
    },
  },
})
